apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
  labels:
    app: busybox
spec:
  containers:
    - name: busybox
      image: ikulyk404/busyboxplus:curl
      command: ["sh", "-c", "sleep 3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
        requests:
          memory: "64Mi"
          cpu: "50m"
  restartPolicy: Never